### PR TITLE
Remove the code that updates resources

### PR DESCRIPTION
**Pull request by rossjones**
Removed the code that updates resource formats.

### CODE REVIEW

**Comment by rossjones** [comment]
@davidread Should I re-deploy QA now with this? Have updated test.

**Comment by davidread** [comment]
Yes, but line 129 needs removing too

**Comment by rossjones** [comment]
Yeah, I found the other place it was used, and it is removed in 2.0

Runs fine on prod2 now.

**Comment by rossjones** [comment]
Deployed to prod3. Restarted priority, both queues now empty.

**Pull request merged**
